-- Generated in Excel from books.csv using:
--	=CONCATENATE("INSERT INTO books(title, author, isbn) VALUES('",SUBSTITUTE([@title], "'","''"),"', '",SUBSTITUTE([@author], "'","''"),"', '", [@isbn], "')")
USE splendid
GO
INSERT INTO books(title, author, isbn) VALUES('The New Manager''s Handbook', 'Morey Stettner ', '')
INSERT INTO books(title, author, isbn) VALUES('Fun with Advanced Mathematics', 'Lewis Galoo', 'NULL')
INSERT INTO books(title, author, isbn) VALUES('Fun with Further Mathematics', 'Lewis Galoo', 'NULL')
INSERT INTO books(title, author, isbn) VALUES('Learn how to be a Demolition Expert', 'Lewis Galoo', 'NULL')
INSERT INTO books(title, author, isbn) VALUES('Learn how to be a Dolphin Trainer', 'Lewis Galoo', 'NULL')
INSERT INTO books(title, author, isbn) VALUES('Learn how to be an Astronaut', 'Lewis Galoo', 'NULL')
INSERT INTO books(title, author, isbn) VALUES('Learn how to be a Supermodel', 'Lewis Galoo', 'NULL')
INSERT INTO books(title, author, isbn) VALUES('Serious Mathematics', 'Lewis Galoo', 'NULL')
INSERT INTO books(title, author, isbn) VALUES('The Elements of Style', ' William Strunk Jr.,  E. B. White,  William Strunk', '020530902X')
INSERT INTO books(title, author, isbn) VALUES('Selenium Simplified - Automated Web Testing with Java and Selenium RC 2nd edition', 'Alan Richardson', '956733239')
INSERT INTO books(title, author, isbn) VALUES('Selenium Simplified - Automated Web Testing with Java and Selenium RC', 'Alan Richardson', '956733239')
INSERT INTO books(title, author, isbn) VALUES('Software Testing:  An ISEB Foundation', 'Brian Hambling, Peter Morgan, Angelina Samaroo, Geoff Thompson, Peter Williams', '1906124760')
INSERT INTO books(title, author, isbn) VALUES('Beginning Android 4 Games Development', 'Mario Zechner, Robert Green ', '1430239875')
INSERT INTO books(title, author, isbn) VALUES('Pro ASP.NET MVC 4', 'Adam Freeman', '')
INSERT INTO books(title, author, isbn) VALUES('Build Your Own Database Driven Website Using PHP and MySQL', 'Kevin Yank ', '')
INSERT INTO books(title, author, isbn) VALUES('Peer Reviews in Software', 'Karl Wiegers', '')
INSERT INTO books(title, author, isbn) VALUES('Perl in a Nutshell (1st ed)', 'Ellen Siever, Stephen Spainhour, Nathan Patwardhan', 'NULL')
INSERT INTO books(title, author, isbn) VALUES('Effortless Flex 4 Development', 'Larry Ullman', '321705947')
INSERT INTO books(title, author, isbn) VALUES('Growing object-oriented software, guided by tests', ' Steve Freeman', '321503627')
INSERT INTO books(title, author, isbn) VALUES('Data Protection & PCI Compliance for Dummies', 'Richard Moulds', 'NULL')
INSERT INTO books(title, author, isbn) VALUES('Foundations of F# (Expert''s Voice in .Net)', 'Robert. Pickering', '1590597575')
INSERT INTO books(title, author, isbn) VALUES('Microsoft Project 2013 ', 'Ben Howard', '')
INSERT INTO books(title, author, isbn) VALUES('Continuous Delivery', 'Jez Humble', '321601912')
INSERT INTO books(title, author, isbn) VALUES('Agile product management with Scrum', ' Roman Pichler', '321605780')
INSERT INTO books(title, author, isbn) VALUES('Joe Celko''s SQL Puzzles and Answers, Second Edition (The Morgan Kaufmann Series in Data Management Systems)', 'Joe Celko', '123735963')
INSERT INTO books(title, author, isbn) VALUES('jQuery cookbook', ' jQuery Community Experts', '596159773')
INSERT INTO books(title, author, isbn) VALUES('Building Web, Cloud, and Mobile Solutions with F#', 'Daniel Mohl', '1-4493-3376-1')
INSERT INTO books(title, author, isbn) VALUES('Special Edition Using Microsoft Commerce Server 2002', ' Don Jones,  Mark D. Scott', '789727633')
INSERT INTO books(title, author, isbn) VALUES('How to Win Friends and Influence People ', 'Dale Carnegie ', '')
INSERT INTO books(title, author, isbn) VALUES('Purely functional data structures', 'Chris Okasaki', '521663504')
INSERT INTO books(title, author, isbn) VALUES('Bulletproof Web Desig', 'Dan Cederholm ', '')
INSERT INTO books(title, author, isbn) VALUES('The Big Book of Me', ' Nina Grunfeld', '1904977499')
INSERT INTO books(title, author, isbn) VALUES('The Big Book of Me', ' Nina Grunfeld', '1904977499')
INSERT INTO books(title, author, isbn) VALUES('Taste Test - Puppet Chef Salt Ansible', 'Matt Jaynes', '')
INSERT INTO books(title, author, isbn) VALUES('WCF Security Guide', 'J.D. Meier, Carlos Farre, Jason Taylor, Prashant Bansode, Steve Gregersen, Madhu Sundararajan, Rob Boucher', 'NULL')
INSERT INTO books(title, author, isbn) VALUES('Professional ASP.NET Design Patterns', 'Scott Millett', '470292784')
INSERT INTO books(title, author, isbn) VALUES('Perl in A Nutshell', ' Ellen Siever,  Stephen Spainhour,  Nathan Patwardhan', '596002416')
INSERT INTO books(title, author, isbn) VALUES('Give and Take', 'Adam Grant ', '')
INSERT INTO books(title, author, isbn) VALUES('Real-World Functional Programming', 'Tomas Petricek, Jon Skeet', '1933988924')
INSERT INTO books(title, author, isbn) VALUES('Domain Driven Design Quickly', 'Abel Avram , Floyd Marinescu ', '1411609255')
INSERT INTO books(title, author, isbn) VALUES('Introducing Microsoft SQL Server 2012 ', 'Ross Mistry, Stacia Misner', '073566515X')
INSERT INTO books(title, author, isbn) VALUES('Working effectively with legacy code', ' Michael C. Feathers', '131177052')
INSERT INTO books(title, author, isbn) VALUES('Working effectively with legacy code', ' Michael C. Feathers', '131177052')
INSERT INTO books(title, author, isbn) VALUES('MCAD Developing and Implementing Web Applications with Microsoft Visual C# .NET and Microsoft Visual Studio  .NET Exam Cram 2 (Exam Cram 70-315)', ' Priti Kalani', '789729016')
INSERT INTO books(title, author, isbn) VALUES('Find Your Dream Job', 'Sarah Wade', '1905736479')
INSERT INTO books(title, author, isbn) VALUES('The Solutions Focus', ' Paul Z. Jackson,  Mark McKergow', '1904838065')
INSERT INTO books(title, author, isbn) VALUES('Beginning ASP.NET 2.0', 'Chris Hart, John Kauffman, David Sussman, Chris Ullman', '764588508')
INSERT INTO books(title, author, isbn) VALUES('Professional ASP.NET MVC 2', 'Jon Galloway, Phil Haack, Scott Hanselman, Scott Gutherie, Rob Conery', '470643188')
INSERT INTO books(title, author, isbn) VALUES('JavaScript Design Patterns', 'Addy Osmani', '978-1449331818')
INSERT INTO books(title, author, isbn) VALUES('Spring recipes', ' Gary Mak', '1590599799')
INSERT INTO books(title, author, isbn) VALUES('Agile Principles, Patterns, and Practices in C# (Robert C. Martin Series)', ' Robert C. Martin,  Micah Martin', '131857258')
INSERT INTO books(title, author, isbn) VALUES('Agile Principles, Patterns, and Practices in C# (Robert C. Martin Series)', ' Robert C. Martin,  Micah Martin', '131857258')
INSERT INTO books(title, author, isbn) VALUES('Flex 4 Cookbook', 'Joshua Noble, Todd Anderson, Garth Braithwaite, Marco Casario, Rich Tretola ', '978-0596805616')
INSERT INTO books(title, author, isbn) VALUES('Akka Concurrency', 'Derek Wyatt', '981531660')
INSERT INTO books(title, author, isbn) VALUES('Self Leadership and the One Minute Manag', ' Ken Blanchard', '7208103')
INSERT INTO books(title, author, isbn) VALUES('On the Shortness of Life', ' Seneca the Younger', '014101881X')
INSERT INTO books(title, author, isbn) VALUES('On Friendship', ' Michel de Montaigne', '141018860')
INSERT INTO books(title, author, isbn) VALUES('Why I Am So Wise (Penguin Great Ideas)', ' Friedrich Nietzsche', '141018976')
INSERT INTO books(title, author, isbn) VALUES('The New Manager''s Handbook (The Mcgraw-Hill Professional Education Series)', ' Morey Stettner', '71413340')
INSERT INTO books(title, author, isbn) VALUES('Microsoft(r) SQL Server(tm) 2005 Developer''s Guide', ' Michael Otey,  Denielle Otey', '72260998')
INSERT INTO books(title, author, isbn) VALUES('Core Java(TM), Volume I--Fundamentals (8th Edition)', ' Cay S. Horstmann,  Gary Cornell', '132354764')
INSERT INTO books(title, author, isbn) VALUES('Effective Java(TM) Programming Language Guide (2nd Edition) (The Java Series)', ' Joshua Bloch', '321356683')
INSERT INTO books(title, author, isbn) VALUES('Practice of System and Network Administration, The (2nd Edition)', ' Thomas A. Limoncelli,  Christina J. Hogan,  Strata R. Chalup', '321492668')
INSERT INTO books(title, author, isbn) VALUES('Eyetracking Web Usability (Voices That Matter)', ' Jakob Nielsen,  Kara Pernice', '321498364')
INSERT INTO books(title, author, isbn) VALUES('Professional ASP.NET 2.0 Special Edition (Wrox Professional Guides)', ' Bill Evjen,  Scott Hanselman,  Devin Rader,  Farhan Muhammad,  Srinivasa Sivakumar', '470041781')
INSERT INTO books(title, author, isbn) VALUES('Professional ASP.NET 2.0 Special Edition (Wrox Professional Guides)', ' Bill Evjen,  Scott Hanselman,  Devin Rader,  Farhan Muhammad,  Srinivasa Sivakumar', '470041781')
INSERT INTO books(title, author, isbn) VALUES('Professional BizTalk Server 2006', ' Darren Jefford,  Kevin B. Smith,  Ewan Fairweather', '470046422')
INSERT INTO books(title, author, isbn) VALUES('Professional BizTalk Server 2006', ' Darren Jefford,  Kevin B. Smith,  Ewan Fairweather', '470046422')
INSERT INTO books(title, author, isbn) VALUES('Programming Interviews Exposed', ' John Mongan,  Noah Suojanen,  Eric Giguère', '047012167X')
INSERT INTO books(title, author, isbn) VALUES('Beginning SharePoint 2007', ' Amanda Murphy,  Shane Perran', '470124490')
INSERT INTO books(title, author, isbn) VALUES('Professional XML (Programmer to Programmer)', ' Bill Evjen,  Kent Sharkey,  Thiru Thangarathinam,  Michael Kay,  Alessandro Vernet,  Sam Ferguson', '471777773')
INSERT INTO books(title, author, isbn) VALUES('Acol Bridge for Bright Beginners (Master Bridge Series)', ' Hugh Kelsey,  Andrew Kambites', '057506174X')
INSERT INTO books(title, author, isbn) VALUES('Learning WCF', ' Michele Bustamante', '596101627')
INSERT INTO books(title, author, isbn) VALUES('Oracle PL/SQL Best Practices', ' Steven Feuerstein', '596514107')
INSERT INTO books(title, author, isbn) VALUES('The Ruby Programming Language', ' David Flanagan,  Yukihiro Matsumoto', '596516177')
INSERT INTO books(title, author, isbn) VALUES('Essential ActionScript 3.0 (Essential)', ' Colin Moock', '596526946')
INSERT INTO books(title, author, isbn) VALUES('The Art of Agile Development', ' James Shore,  Shane Warden', '596527675')
INSERT INTO books(title, author, isbn) VALUES('Microsoft ISA Server 2000', ' Zubair Alexander', '672321009')
INSERT INTO books(title, author, isbn) VALUES('Microsoft Exchange Server 2003 Unleashed', ' Rand Morimoto', '672328070')
INSERT INTO books(title, author, isbn) VALUES('Microsoft Exchange Server 2003 Unleashed', ' Rand Morimoto', '672328070')
INSERT INTO books(title, author, isbn) VALUES('Microsoft(R) SharePoint(R) 2007 Development Unleashed', ' Kevin Hoffman,  Robert Foster', '672329034')
INSERT INTO books(title, author, isbn) VALUES('Handbook of relational database design', ' Candace C. Fleming', '201114348')
INSERT INTO books(title, author, isbn) VALUES('Inside Active Directory', ' Sakari Kouti,  Mika Seitsonen', '201616211')
INSERT INTO books(title, author, isbn) VALUES('The Pragmatic Programmer', ' Andrew Hunt,  David Thomas', '020161622X')
INSERT INTO books(title, author, isbn) VALUES('Meetings That Work', ' Catherine Widdicombe', '718830016')
INSERT INTO books(title, author, isbn) VALUES('Programming Pearls (2nd Edition)', ' Jon Bentley', '201657880')
INSERT INTO books(title, author, isbn) VALUES('Designing Enterprise Applications with the Java(TM) 2 Platform (Enterprise Edition)', ' Nicholas Kassem,  Nick Kassem,  Enterprise Team', '201702770')
INSERT INTO books(title, author, isbn) VALUES('Advanced Visual Basic 6', ' Matthew J. Curland', '201707128')
INSERT INTO books(title, author, isbn) VALUES('Metrics and Models in Software Quality Engineering (2nd Edition)', ' Stephen H. Kan', '201729156')
INSERT INTO books(title, author, isbn) VALUES('Microsoft windows security resource kit', ' Ben Smith', '735621748')
INSERT INTO books(title, author, isbn) VALUES('Microsoft  Mobile Development Handbook', ' Andy Wigley,  Daniel Moth,  Peter Foot', '735623589')
INSERT INTO books(title, author, isbn) VALUES('How to break software', ' James A. Whittaker', '201796198')
INSERT INTO books(title, author, isbn) VALUES('The mythical man-month', ' Frederick P. Brooks', '201835959')
INSERT INTO books(title, author, isbn) VALUES('A guide to the SQL standard', ' C. J. Date', '201964260')
INSERT INTO books(title, author, isbn) VALUES('How to Set Up and Run Your Own Business (Creating Success)', ' Daily Telegraph', '749433086')
INSERT INTO books(title, author, isbn) VALUES('Sales Meetings That Work', ' Richard Cavalier', '075965736X')
INSERT INTO books(title, author, isbn) VALUES('Read This', ' Robert Gentle', '273656503')
INSERT INTO books(title, author, isbn) VALUES('Struts 2 Design and Programming', 'Budi. Kurniawan', '980331609')
INSERT INTO books(title, author, isbn) VALUES('Dreaming in Code', ' Scott Rosenberg', '1400082471')
INSERT INTO books(title, author, isbn) VALUES('Starting Struts 2', ' Ian Roughley', '1430320338')
INSERT INTO books(title, author, isbn) VALUES('Patterns of Enterprise Application Architecture', ' Martin Fowler', '321127420')
INSERT INTO books(title, author, isbn) VALUES('.NET Patterns', ' Christian Thilmany', '321130022')
INSERT INTO books(title, author, isbn) VALUES('Test Driven Development', ' Kent Beck', '321146530')
INSERT INTO books(title, author, isbn) VALUES('Lean Software Development', ' Mary Poppendieck,  Tom Poppendieck', '321150783')
INSERT INTO books(title, author, isbn) VALUES('The common language infrastructure annotated standard', ' James S. Miller', '321154932')
INSERT INTO books(title, author, isbn) VALUES('PHP and MySQL for dynamic Web sites', ' Larry E. Ullman', '321186486')
INSERT INTO books(title, author, isbn) VALUES('The non-designers design book', 'Robin Williams', '321193857')
INSERT INTO books(title, author, isbn) VALUES('User Stories Applied', ' Mike Cohn', '321205685')
INSERT INTO books(title, author, isbn) VALUES('User Stories Applied', ' Mike Cohn', '321205685')
INSERT INTO books(title, author, isbn) VALUES('Macromedia Flash MX 2004', ' Jen deHaan', '321213424')
INSERT INTO books(title, author, isbn) VALUES('Macromedia Flash MX 2004 ActionScript', ' Derek Franklin,  Jobe Makar', '321213432')
INSERT INTO books(title, author, isbn) VALUES('Effective C#', ' Bill Wagner', '321245660')
INSERT INTO books(title, author, isbn) VALUES('Extreme Programming Explained', ' Kent Beck,  Cynthia Andres', '321278658')
INSERT INTO books(title, author, isbn) VALUES('Adobe Photoshop CS2 Classroom in a Book', ' Adobe Systems Inc.', '321321847')
INSERT INTO books(title, author, isbn) VALUES('Don''t Make Me Think', ' Steve Krug', '321344758')
INSERT INTO books(title, author, isbn) VALUES('How to break Web software', ' James A. Whittaker', '321369440')
INSERT INTO books(title, author, isbn) VALUES('Implementing Lean Software Development', ' Mary Poppendieck,  Tom Poppendieck', '321437381')
INSERT INTO books(title, author, isbn) VALUES('The Old New Thing', ' Raymond Chen', '321440307')
INSERT INTO books(title, author, isbn) VALUES('Beginning Game Development with Python and Pygame', ' Will McGugan', '1590598725')
INSERT INTO books(title, author, isbn) VALUES('Practical Apache Struts 2 Web 2.0 Projects (Practical Projects)', ' Ian Roughley', '1590599039')
INSERT INTO books(title, author, isbn) VALUES('Practical Apache Struts 2 Web 2.0 Projects (Practical Projects)', ' Ian Roughley', '1590599039')
INSERT INTO books(title, author, isbn) VALUES('Painless Project Management with FogBugz', ' Mike Gunderloy', '1590599144')
INSERT INTO books(title, author, isbn) VALUES('MCSA/MCSE Exam 70-291 Study Guide and Training System', ' Dr. Thomas W. Shinder,  Dan Douglas,  Hal Kurz,  Syngress Media,  Thomas W. Shinder,  Debra Littlejohn Shinder', '1931836922')
INSERT INTO books(title, author, isbn) VALUES('LINQ in Action', ' Fabrice Marguerie,  Steve Eichert,  Jim Wooley', '1933988169')
INSERT INTO books(title, author, isbn) VALUES('Cool Restaurants Istanbul', 'Cool Restaurants', '3832791159')
INSERT INTO books(title, author, isbn) VALUES('Core Java, Vol. 2', ' Cay S. Horstmann,  Gary Cornell', '132354799')
INSERT INTO books(title, author, isbn) VALUES('Designing Social Web Applications (Voices That Matter)', ' Joshua Porter', '321534921')
INSERT INTO books(title, author, isbn) VALUES('Harnessing Hibernate', 'James Elliott, Tim O''Brien, Ryan Fowler', '596517726')
INSERT INTO books(title, author, isbn) VALUES('Online Marketing', ' Ravi Damani,  Chetan Damani,  Dana Farbo,  Jane Linton', '954905539')
INSERT INTO books(title, author, isbn) VALUES('The Innovator''s Dilemma', ' Clayton M. Christensen', '60521996')
INSERT INTO books(title, author, isbn) VALUES('Scientific Computing on Itanium-Based Systems', ' Marius Cornea,  John Harrison,  Ping Tak Peter Tang', '971288771')
INSERT INTO books(title, author, isbn) VALUES('Scrum and XP from the Trenches', ' Henrik Kniberg', '1430322640')
INSERT INTO books(title, author, isbn) VALUES('Lessons Learned in Software Testing', ' Cem Kaner,  James Bach,  Bret Pettichord', '471081124')
INSERT INTO books(title, author, isbn) VALUES('COM and the battle for the middle tier', ' Roger Sessions', '471317179')
INSERT INTO books(title, author, isbn) VALUES('MDX Solutions', ' George Spofford', '471400467')
INSERT INTO books(title, author, isbn) VALUES('Java testing patterns', 'Jon Thomas, Matthew Young', '047144846X')
INSERT INTO books(title, author, isbn) VALUES('Struts 2 in Action', ' Don Brown,  Chad Davis,  Scott Stanlick', '193398807X')
INSERT INTO books(title, author, isbn) VALUES('ASP.NET 2.0 Instant Results (Programmer to Programmer)', ' Imar Spaanjaars,  Paul Wilton,  Shawn Livermore', '471749516')
INSERT INTO books(title, author, isbn) VALUES('Pattern-Oriented Software Architecture Volume 1', ' Frank Buschmann,  Regine Meunier,  Hans Rohnert,  Peter Sommerlad,  Michael Stal', '471958697')
INSERT INTO books(title, author, isbn) VALUES('Numerical solution of partial differential equations', ' K. W. Morton', '521607930')
INSERT INTO books(title, author, isbn) VALUES('Introduction to lattices and order', ' B. A. Davey', '521784514')
INSERT INTO books(title, author, isbn) VALUES('Object-oriented programming in Oberon-2', ' Hanspeter Mössenböck', '3540600620')
INSERT INTO books(title, author, isbn) VALUES('Java servlet programming', ' Jason Hunter', '596000405')
INSERT INTO books(title, author, isbn) VALUES('VBScript pocket reference', ' Matt Childs', '596001266')
INSERT INTO books(title, author, isbn) VALUES('Ruby in a nutshell', ' Yukihiro Matsumoto', '596002149')
INSERT INTO books(title, author, isbn) VALUES('Network Security with OpenSSL', ' John Viega,  Matt Messier,  Pravir Chandra', '059600270X')
INSERT INTO books(title, author, isbn) VALUES('TCP/IP Network Administration (3rd Edition; O''Reilly Networking)', ' Craig Hunt', '596002971')
INSERT INTO books(title, author, isbn) VALUES('Shared source CLI essentials', ' David Stutz', '059600351X')
INSERT INTO books(title, author, isbn) VALUES('sed and awk Pocket Reference', ' Arnold Robbins', '596003528')
INSERT INTO books(title, author, isbn) VALUES('sed and awk Pocket Reference', ' Arnold Robbins', '596003528')
INSERT INTO books(title, author, isbn) VALUES('Java Swing, Second Edition', ' James Elliott,  Marc Loy,  David Wood,  Brian Cole', '596004087')
INSERT INTO books(title, author, isbn) VALUES('Enterprise JavaBeans', ' Richard Monson-Haefel', '059600530X')
INSERT INTO books(title, author, isbn) VALUES('CVS Pocket Reference', ' Gregor Purdy,  Gregor N. Purdy', '596005679')
INSERT INTO books(title, author, isbn) VALUES('Essential ActionScript 3.0', ' Colin Moock', '596006527')
INSERT INTO books(title, author, isbn) VALUES('Head First design patterns', 'Eric Freeman, Elisabeth Robson, Bert Bates, Kathy Sierra', '596007124')
INSERT INTO books(title, author, isbn) VALUES('Java In A Nutshell', ' David Flanagan', '596007736')
INSERT INTO books(title, author, isbn) VALUES('Head First Object-Oriented Analysis and Design', ' Brett D. McLaughlin,  Gary Pollice,  Dave West', '596008678')
INSERT INTO books(title, author, isbn) VALUES('Switching to VoIP', ' Ted Wallingford', '596008686')
INSERT INTO books(title, author, isbn) VALUES('Enterprise JavaBeans 3.0 (5th Edition)', ' Bill Burke,  Richard Monson-Haefel', '059600978X')
INSERT INTO books(title, author, isbn) VALUES('Web Design in a Nutshell', ' Jennifer Niederst Robbins,  Tantek Çelik,  Derek Featherstone,  Aaron Gustafson', '596009879')
INSERT INTO books(title, author, isbn) VALUES('Unix in a Nutshell', ' Arnold Robbins', '596100299')
INSERT INTO books(title, author, isbn) VALUES('PHP in a Nutshell', ' Paul Hudson,  Paul Hudson', '596100671')
INSERT INTO books(title, author, isbn) VALUES('SharePoint Office Pocket Guide', ' Jeff Webb', '596101120')
INSERT INTO books(title, author, isbn) VALUES('Java Enterprise in a Nutshell', ' Jim Farley,  William Crawford,  Prakash Malani,  John Norman,  Justin Gehtland', '596101422')
INSERT INTO books(title, author, isbn) VALUES('SUSE Linux', ' Chris Brown', '059610183X')
INSERT INTO books(title, author, isbn) VALUES('Learning C# 2005', ' Jesse Liberty,  Brian MacDonald', '596102097')
INSERT INTO books(title, author, isbn) VALUES('Ruby Cookbook (Cookbooks (O''Reilly))', ' Lucas Carlson,  Leonard Richardson', '596523696')
INSERT INTO books(title, author, isbn) VALUES('HTML & XHTML', ' Chuck Musciano,  Bill Kennedy', '596527322')
INSERT INTO books(title, author, isbn) VALUES('CSS', ' Eric Meyer', '596527330')
INSERT INTO books(title, author, isbn) VALUES('Ajax on Rails', ' Scott Raymond', '596527446')
INSERT INTO books(title, author, isbn) VALUES('Pure Visual Basic', ' Dan Fox', '067231598X')
INSERT INTO books(title, author, isbn) VALUES('Sams Teach Yourself Active Server Pages 3.0 in 21 Days', ' Scott Mitchell,  James Atkinson', '672318636')
INSERT INTO books(title, author, isbn) VALUES('Sams Teach Yourself Transact-SQL in 21 Days (2nd Edition)', ' Lowell Mauer', '672319675')
INSERT INTO books(title, author, isbn) VALUES('Sams Teach Yourself Transact-SQL in 21 Days (2nd Edition)', ' Lowell Mauer', '672319675')
INSERT INTO books(title, author, isbn) VALUES('Sams teach yourself SQL in 21 days', ' Ryan K. Stephens', '672324512')
INSERT INTO books(title, author, isbn) VALUES('Sams teach yourself Microsoft SQL server 2000 in 21 days', ' Richard Waymire', '672324695')
INSERT INTO books(title, author, isbn) VALUES('Microsoft BizTalk server 2004 unleashed', 'Scott Woodgate, Stephen Mohr, Brian Loesgen', '672325985')
INSERT INTO books(title, author, isbn) VALUES('Macromedia Flash MX Professional 2004 Unleashed', ' David Vogeleer,  Matthew Pizzi', '067232606X')
INSERT INTO books(title, author, isbn) VALUES('Windows Presentation Foundation Unleashed (WPF) (Unleashed)', ' Adam Nathan', '672328917')
INSERT INTO books(title, author, isbn) VALUES('The 7 Habits of Highly Effective People', ' Stephen R. Covey', '684858398')
INSERT INTO books(title, author, isbn) VALUES('MCDBA SQL Server 2000 database design study guide (exam 70-229)', ' Jeffrey Bane', '72126930')
INSERT INTO books(title, author, isbn) VALUES('Design patterns', ' Erich Gamma', '201633612')
INSERT INTO books(title, author, isbn) VALUES('Microsoft Backoffice Small Business Server 4.5 Resource Kit', ' Microsoft Corporation.', '735605777')
INSERT INTO books(title, author, isbn) VALUES('Programming Microsoft Office 2000 Web Components (Microsoft Programming Series)', ' Dave Stearns', '073560794X')
INSERT INTO books(title, author, isbn) VALUES('Microsoft(r) SQL Server(tm) 2000 Analysis Services Step by Step', ' OLAP Train,  Reed Jacobson', '735609047')
INSERT INTO books(title, author, isbn) VALUES('Introducing Microsoft(r) Exchange 2000 Server', ' Joanne Woodcock', '735609608')
INSERT INTO books(title, author, isbn) VALUES('Designing Secure Web-Based Applications for Microsoft(r) Windows(r) 2000', ' Michael Howard', '735609950')
INSERT INTO books(title, author, isbn) VALUES('Inside Microsoft SQL Server 2000', ' Kalen Delaney', '735609985')
INSERT INTO books(title, author, isbn) VALUES('MCSE Microsoft SQL Server 2000 Database Design and Implementation', ' Sharon Bjeletich,  Eddy Hahn', '073561251X')
INSERT INTO books(title, author, isbn) VALUES('Programming Windows with C# (Core Reference)', ' Charles Petzold', '735613702')
INSERT INTO books(title, author, isbn) VALUES('MCAD/MCSD Self-Paced Training Kit', ' Microsoft Corporation.,  Microsoft Corporation.', '735615861')
INSERT INTO books(title, author, isbn) VALUES('Microsoft .NET XML Web Services Step by Step', ' Adam Freeman,  Allen Jones,  Adam Freeman', '735617201')
INSERT INTO books(title, author, isbn) VALUES('Application Architecture for .NET', ' Microsoft Corporation.', '735618372')
INSERT INTO books(title, author, isbn) VALUES('Programming Microsoft  .NET XML Web Services (Pro-Developer)', ' Damien Foggon,  Daniel Maharry,  Chris Ullman,  Karli Watson', '735619123')
INSERT INTO books(title, author, isbn) VALUES('Code Complete', ' Steve McConnell', '735619670')
INSERT INTO books(title, author, isbn) VALUES('Introducing ASP.NET 2.0', ' Dino Esposito', '735620245')
INSERT INTO books(title, author, isbn) VALUES('Inside Microsoft SQL Server 2005', ' Kalen Delaney', '735621055')
INSERT INTO books(title, author, isbn) VALUES('Programming INDIGO', ' David Pallmann', '735621519')
INSERT INTO books(title, author, isbn) VALUES('Programming Microsoft  ASP.NET 2.0 Applications', ' Dino Esposito', '735621772')
INSERT INTO books(title, author, isbn) VALUES('Programming Microsoft  ASP.NET 2.0 Applications', ' Dino Esposito', '735621772')
INSERT INTO books(title, author, isbn) VALUES('Inside Microsoft SQL Server 2005', ' Itzik Ben-gan,  Dejan Sarka,  Roger Wolter', '735621977')
INSERT INTO books(title, author, isbn) VALUES('Inside Microsoft SQL Server 2005', ' Itzik Ben-gan,  Dejan Sarka,  Roger Wolter', '735621977')
INSERT INTO books(title, author, isbn) VALUES('Programming Microsoft  ADO.NET 2.0 Core Reference', ' David Sceppa', '073562206X')
INSERT INTO books(title, author, isbn) VALUES('MCTS Self-Paced Training Kit (Exam 70-536)', ' Tony Northrup,  Shawn Wildermuth,  Bill Ryan', '735622779')
INSERT INTO books(title, author, isbn) VALUES('Microsoft  Windows  Small Business Server 2003 R2 Administrator''s Companion (Pro-Administrator''s Companion)', ' Charlie Russel,  Sharon Crawford', '735622809')
INSERT INTO books(title, author, isbn) VALUES('Microsoft  Office SharePoint  Server 2007 Administrator''s Companion', ' Bill English,  The Microsoft SharePoint Community Experts', '735622825')
INSERT INTO books(title, author, isbn) VALUES('Inside Microsoft SQL Server 2005', ' Itzik Ben-Gan,  Lubor Kollar,  Dejan Sarka', '735623139')
INSERT INTO books(title, author, isbn) VALUES('MCTS Self-Paced Training Kit (Exam 70-526)', ' Matthew A. Stoecker,  Steven J. Stein,  Tony Northrup', '735623333')
INSERT INTO books(title, author, isbn) VALUES('MCTS Self-Paced Training Kit (Exam 70-528): Microsoft  .NET Framework 2.0 Web-Based Client Development (Pro Certification)', ' Glenn Johnson,  Tony Northrup', '735623341')
INSERT INTO books(title, author, isbn) VALUES('MCPD Self-Paced Training Kit (Exam 70-547)', ' Mike Snell,  Bruce Johnson,  Brian C. Lanham,  Shawn Wildermuth,  Sara Morgan', '735623406')
INSERT INTO books(title, author, isbn) VALUES('Macromedia Flash MX 2004 Killer Tips', ' Shane Elliott', '735713839')
INSERT INTO books(title, author, isbn) VALUES('Conceptual blockbusting', 'James L. Adams', '738205370')
INSERT INTO books(title, author, isbn) VALUES('Successful Presentation Skills', ' Andrew J. Bradbury', '749432594')
INSERT INTO books(title, author, isbn) VALUES('Getting Things Done', ' David Allen', '749922648')
INSERT INTO books(title, author, isbn) VALUES('Meditations', ' Marcus Aurelius', '753820161')
INSERT INTO books(title, author, isbn) VALUES('NT Network Plumbing', ' Tony Northrup', '076453209X')
INSERT INTO books(title, author, isbn) VALUES('Microsoft Outlook 2000 Programming Bible', ' Jeffrey A. Kent,  Davaid G. Jung', '764546503')
INSERT INTO books(title, author, isbn) VALUES('Professional ASP.NET 1.1', ' Alex Homer,  Dave Sussman,  Rob Howard,  Brian Francis,  Karli Watson,  Richard Anderson', '764558900')
INSERT INTO books(title, author, isbn) VALUES('Paint Shop Pro 9 for dummies', ' David C. Kay', '764579355')
INSERT INTO books(title, author, isbn) VALUES('ASP.NET 2.0 Website Programming', ' Marco Bellinaso', '764584642')
INSERT INTO books(title, author, isbn) VALUES('Photoshop CS2 Bible', ' Laurie Ulrich Fuller,  Deke McClelland', '764589725')
INSERT INTO books(title, author, isbn) VALUES('Professional ASP.NET 2.0 security, membership, and role management', ' Stefan Schackow', '764596985')
INSERT INTO books(title, author, isbn) VALUES('Mastering Windows 2000 Server', ' Brian M. Smith,  Doug Toombs,  Mark Minasi', '782140432')
INSERT INTO books(title, author, isbn) VALUES('Mastering Windows Server 2003', 'Microsoft', '782141307')
INSERT INTO books(title, author, isbn) VALUES('C# Complete', ' Sybex', '782142036')
INSERT INTO books(title, author, isbn) VALUES('The IT Consultant ', ' Rick Freedman,  Rick Freeman', '787951730')
INSERT INTO books(title, author, isbn) VALUES('Clean code', 'Robert C. Martin', '132350882')
INSERT INTO books(title, author, isbn) VALUES('JRuby Cookbook', 'Justin Edelson', '059651980X')
INSERT INTO books(title, author, isbn) VALUES('Domain-Driven Design', ' Eric Evans', '321125215')
INSERT INTO books(title, author, isbn) VALUES('Domain-Driven Design', ' Eric Evans', '978-0321125217')
INSERT INTO books(title, author, isbn) VALUES('MCAD Developing and Implementing Web Applications with Microsoft Visual C# .NET and Microsoft Visual Studio  .NET Exam Cram 2 (Exam Cram 70-315)', ' Priti Kalani', '789729016')
INSERT INTO books(title, author, isbn) VALUES('Special Edition Using Macromedia Director MX', ' Gary Rosenzweig', '789729032')
INSERT INTO books(title, author, isbn) VALUES('Administering IIS4', ' Mitch Tulloch', '70655367')
INSERT INTO books(title, author, isbn) VALUES('Matrix computations', ' Gene H. Golub', '801854148')
INSERT INTO books(title, author, isbn) VALUES('Agile testing', ' Lisa Crispin', '321534468')
INSERT INTO books(title, author, isbn) VALUES('Oracle Database 10g', ' Kevin Loney', '72253517')
INSERT INTO books(title, author, isbn) VALUES('The Hunger Games', ' Suzanne Collins', '9780440000000')
INSERT INTO books(title, author, isbn) VALUES('Succeeding with agile', ' Mike Cohn', '321579364')
INSERT INTO books(title, author, isbn) VALUES('The art of game design', ' Jesse Schell', '123694965')
INSERT INTO books(title, author, isbn) VALUES('Applied Microsoft .NET Framework Programming', ' Jeffrey Richter', '735614229')
INSERT INTO books(title, author, isbn) VALUES('Schaum''s Outline of UML (Schaum''s Outlines)', ' Simon Bennett,  John Skelton,  Ken Lunn', '77107411')
INSERT INTO books(title, author, isbn) VALUES('REST in Practice', 'Jim Webber, Savas Parastatidis, Ian Robinson', '596805829')
INSERT INTO books(title, author, isbn) VALUES('The C Programming Language', 'Brian W Kernighan, Dennis M Ritchie', '131103628')
INSERT INTO books(title, author, isbn) VALUES('Programming WCF Services', 'Juval Lowy', '596805489')
INSERT INTO books(title, author, isbn) VALUES('Microsoft Silverlight 4 Data and Services Cookbook', 'Gill Cleeren', '1847199844')
INSERT INTO books(title, author, isbn) VALUES('Professional Enterprise .NET', 'Microsoft', '470447613')
INSERT INTO books(title, author, isbn) VALUES('Pro Silverlight 3 in C#', 'Matthew MacDonald', '1430223812')
INSERT INTO books(title, author, isbn) VALUES('Never Eat Alone', ' Keith Ferrazzi,  Tahl Raz', '385512058')
INSERT INTO books(title, author, isbn) VALUES('Shades of grey', 'Jasper Fforde', '340963050')
INSERT INTO books(title, author, isbn) VALUES('Cloud Computing Explained', 'John Rhoton', '956355609')
INSERT INTO books(title, author, isbn) VALUES('Professional ASP.NET MVC 1.0', 'Microsoft', '470384611')
INSERT INTO books(title, author, isbn) VALUES('New Programmer''s Survival Manual', 'Josh Carter', '1934356816')
INSERT INTO books(title, author, isbn) VALUES('Professional ATL COM programming.', ' Richard Grimes', '1861001401')
INSERT INTO books(title, author, isbn) VALUES('Peopleware', ' Tom DeMarco', '932633439')
INSERT INTO books(title, author, isbn) VALUES('Waltzing With Bears', ' Tom DeMarco,  Timothy Lister', '932633609')
INSERT INTO books(title, author, isbn) VALUES('Scrumban', 'Corey Ladas', '578002140')
INSERT INTO books(title, author, isbn) VALUES('C# in depth', ' Jon Skeet', '1935182471')
INSERT INTO books(title, author, isbn) VALUES('JavaScript', ' David Flanagan', '596805527')
INSERT INTO books(title, author, isbn) VALUES('Javascript Web Applications', 'Alex MacCaw', '144930351X')
INSERT INTO books(title, author, isbn) VALUES('RESTful Web Services', 'Leonard Richardson, Sam Ruby', '596529260')
INSERT INTO books(title, author, isbn) VALUES('Agile web development with rails', ' Sam Ruby', '1934356549')
INSERT INTO books(title, author, isbn) VALUES('The PHP Anthology', ' Harry Fuecks', '957921853')
INSERT INTO books(title, author, isbn) VALUES('Real-World Functional Programming', 'Tomas Petricek, Jon Skeet', '978-1933988924')
INSERT INTO books(title, author, isbn) VALUES('Spring in action', ' Craig Walls', '1935182358')
INSERT INTO books(title, author, isbn) VALUES('Life and Fate', ' Vasiliĭ Semenovich Grossman', '99506165')
INSERT INTO books(title, author, isbn) VALUES('Microsoft Outlook Programming, Jumpstart for Administrators, Developers, and Power Users', ' Sue Mosher', '1555582869')
INSERT INTO books(title, author, isbn) VALUES('Developing Time-Oriented Database Applications in SQL (Morgan Kaufmann Series in Data Management Systems)', ' Richard T. Snodgrass,  Christian S. Jensen', '1558604367')
INSERT INTO books(title, author, isbn) VALUES('UNIX System Programming  for System VR4', ' Dave Curry', '1565921631')
INSERT INTO books(title, author, isbn) VALUES('UNIX System Programming  for System VR4', ' Dave Curry', '1565921631')
INSERT INTO books(title, author, isbn) VALUES('Windows NT TCP/IP network administration', ' Craig Hunt', '1565923774')
INSERT INTO books(title, author, isbn) VALUES('Java foundation classes in a nutshell', ' David Flanagan', '1565924886')
INSERT INTO books(title, author, isbn) VALUES('VB Shell Programming (Visual Basic)', ' J.P. Hamilton', '1565926706')
INSERT INTO books(title, author, isbn) VALUES('Programming the Perl DBI', ' Alligator Descartes', '1565926994')
INSERT INTO books(title, author, isbn) VALUES('Developing ASP components', ' Shelley Powers', '1565927508')
INSERT INTO books(title, author, isbn) VALUES('ASP in a Nutshell', ' Keyton Weissinger', '1565928431')
INSERT INTO books(title, author, isbn) VALUES('Conquering carpal tunnel syndrome and other repetitive strain injuries', ' Sharon J. Butler', '978-1572240391')
INSERT INTO books(title, author, isbn) VALUES('Inside MAPI', ' Irving De la Cruz', '1572313129')
INSERT INTO books(title, author, isbn) VALUES('Inside COM', ' Dale Rogerson', '1572313498')
INSERT INTO books(title, author, isbn) VALUES('The One Minute Manager', ' Kenneth H. Blanchard,  Spencer Johnson', '7107927')
INSERT INTO books(title, author, isbn) VALUES('The Referral of a Lifetime', ' Tim Templeton,  Lynda Rutledge Stephenson', '1576753212')
INSERT INTO books(title, author, isbn) VALUES('Graphic Java 2, Volume 2', 'David Geary', '130796670')
INSERT INTO books(title, author, isbn) VALUES('The definitive guide to Windows Installer', ' Phil Wilson', '1590592972')
INSERT INTO books(title, author, isbn) VALUES('Holub on Patterns', ' Allen Holub', '159059388X')
INSERT INTO books(title, author, isbn) VALUES('The Best Software Writing I', ' Joel Spolsky', '1590595009')
INSERT INTO books(title, author, isbn) VALUES('Foundations of AOP for J2EE Development (Foundation)', ' Renaud Pawlak,  Jean-Philippe Retaillé,  Lionel Seinturier', '1590595076')
INSERT INTO books(title, author, isbn) VALUES('Expert Oracle Database Architecture', ' Thomas Kyte', '1590595300')
INSERT INTO books(title, author, isbn) VALUES('The Definitive Guide to MySQL 5, Third Edition (Definitive Guide)', 'Michael Kofler', '1590595351')
INSERT INTO books(title, author, isbn) VALUES('Beginning PHP and MySQL 5', ' W. Jason Gilmore', '1590595521')
INSERT INTO books(title, author, isbn) VALUES('Expert Spring MVC and Web Flow (Expert)', ' Seth Ladd,  Darren Davison,  Steven Devijver,  Colin Yates', '159059584X')
INSERT INTO books(title, author, isbn) VALUES('Pro PHP XML and Web Services (Pro)', ' Robert Richards', '1590596331')
INSERT INTO books(title, author, isbn) VALUES('Pro EJB 3', ' Mike Keith,  Merrick Schincariol', '1590596455')
INSERT INTO books(title, author, isbn) VALUES('Blue Ocean Strategy', ' W. Chan Kim,  Renée Mauborgne', '1591396190')
INSERT INTO books(title, author, isbn) VALUES('Object-Oriented PHP', ' Peter Lavin', '1593270771')
INSERT INTO books(title, author, isbn) VALUES('Unix Network Programming, Vol. 1', ' W. Richard Stevens,  Bill Fenner,  Andrew M. Rudoff,  Richard W. Stevens', '131411551')
INSERT INTO books(title, author, isbn) VALUES('Agile estimating and planning', ' Mike Cohn', '131479415')
INSERT INTO books(title, author, isbn) VALUES('Crossing the Chasm', ' Geoffrey A. Moore', '1841120634')
INSERT INTO books(title, author, isbn) VALUES('Dealing with Darwin', ' Geoffrey A Moore         ', '1841127175')
INSERT INTO books(title, author, isbn) VALUES('The One Minute Manager Meets the Monkey (One Minute Manager)', ' Kenneth H. Blanchard', '7116985')
INSERT INTO books(title, author, isbn) VALUES('Visual Basic 6 how to program', ' Harvey M. Deitel', '134569555')
INSERT INTO books(title, author, isbn) VALUES('Beginning ATL 3 COM programming', ' Richard Grimes', '1861001207')
INSERT INTO books(title, author, isbn) VALUES('Professional SQL Server 7.0 Programming', ' Rob Vieira', '1861002319')
INSERT INTO books(title, author, isbn) VALUES('Outlook 2000 VBA Programmers Reference', ' Dwayne Gifford', '186100253X')
INSERT INTO books(title, author, isbn) VALUES('ADO 2.1 programmer''s reference', ' David Sussman', '1861002688')
INSERT INTO books(title, author, isbn) VALUES('Professional Java Server Programming', ' Sing Li,  Paul Houle,  Mark Wilcox,  Ron Phillips,  Piroz Mohseni,  Stefan Zeiger,  Hans Bergsten,  Matthew Ferris,  Jason Diamond,  Mike Bogovich,  Marc Fleury,  Krishna Vedati,  Ari Halberstadt,  Andrew Patzer', '1861002777')
INSERT INTO books(title, author, isbn) VALUES('Professional XSL', 'v', '1861003579')
INSERT INTO books(title, author, isbn) VALUES('Professional JSP 2nd Edition', ' Simon Brown,  Robert Burdick,  Jayson Falkner,  Ben Galbraith,  Rod Johnson,  Larry Kim,  Casey Kochmer,  Thor Kristmundsson,  Sing Li', '1861004958')
INSERT INTO books(title, author, isbn) VALUES('The Art of Innovation', ' Thomas Kelley', '186197583X')
INSERT INTO books(title, author, isbn) VALUES('Code Centric', ' Garth Wells', '1893115836')
INSERT INTO books(title, author, isbn) VALUES('Bitter Java', ' Bruce Tate', '193011043X')
INSERT INTO books(title, author, isbn) VALUES('Struts in Action', ' Ted Husted,  Cedric Dumoulin,  George Franciscus,  David Winterfeldt,  Craig R. McClanahan', '1930110502')
INSERT INTO books(title, author, isbn) VALUES('Dr. Tom Shinder''s Configuring ISA Server 2004', ' Thomas W. Shinder,  Martin Grasdal', '1931836191')
INSERT INTO books(title, author, isbn) VALUES('Dr. Tom Shinder''s ISA Server and Beyond', ' Thomas W. Shinder,  Martin Grasdal,  Debra Littlejohn Shinder', '1931836663')
INSERT INTO books(title, author, isbn) VALUES('Theory of Fun for Game Design', ' Raph Koster', '1932111972')
INSERT INTO books(title, author, isbn) VALUES('Hibernate in action', 'Christian. Bauer', '193239415X')
INSERT INTO books(title, author, isbn) VALUES('Groovy in Action', ' Dierk Koenig,  Andrew Glover,  Paul King,  Guillaume Laforge,  Jon Skeet', '1932394842')
INSERT INTO books(title, author, isbn) VALUES('Adobe Photoshop CS4 - Classroom in a book', '', 'NULL')
INSERT INTO books(title, author, isbn) VALUES('Classroom in a Book: The official training workbook from Adobe Systems', '', 'NULL')
INSERT INTO books(title, author, isbn) VALUES('Inside Microsoft SQL Server 2008: T-SQL Querying', 'Itzik Ben-Gan', 'NULL')
INSERT INTO books(title, author, isbn) VALUES('Java Server Programming ', 'David Flanagan', 'NULL')
INSERT INTO books(title, author, isbn) VALUES('Java How to Program', '', 'NULL')
INSERT INTO books(title, author, isbn) VALUES('Programming Groovy', 'Venkat Subramaniam', 'NULL')
INSERT INTO books(title, author, isbn) VALUES('UML for Systems Engineering: watching the wheels', 'Jon Holt', 'NULL')
INSERT INTO books(title, author, isbn) VALUES('The Truth About Power', '', 'NULL')
INSERT INTO books(title, author, isbn) VALUES('Guide - Across Asia on the cheap', '', 'NULL')
INSERT INTO books(title, author, isbn) VALUES('Guide - Dublin', '', 'NULL')
INSERT INTO books(title, author, isbn) VALUES('Guide - Greek Islands', '', 'NULL')
INSERT INTO books(title, author, isbn) VALUES('Guide - Istanbul', '', 'NULL')
INSERT INTO books(title, author, isbn) VALUES('Guide - Melbourne', '', 'NULL')
INSERT INTO books(title, author, isbn) VALUES('Guide - Provence & the Cote d''Azur - The Rough Guide', 'Kate Baillie', 'NULL')
INSERT INTO books(title, author, isbn) VALUES('Master atlas of Greater London', '', 'NULL')
INSERT INTO books(title, author, isbn) VALUES('Oxford Dictionary', '', 'NULL')
INSERT INTO books(title, author, isbn) VALUES('Mini LondonA-Z', '', 'NULL')
INSERT INTO books(title, author, isbn) VALUES('No-Limit Texas Hold''Em For Winners', 'Andrea Shavik, Dan Shavik', 'NULL')
INSERT INTO books(title, author, isbn) VALUES('Don''t Panic - Mobile Developers Guide to the Galaxy', '', 'NULL')
INSERT INTO books(title, author, isbn) VALUES('Visual C++6 Programming', 'Richard Grimes', 'NULL')
INSERT INTO books(title, author, isbn) VALUES('Building Applications with Microsoft Outlook 98', '', 'NULL')
INSERT INTO books(title, author, isbn) VALUES('Designing and Developing ASP.NET Applications Using the Microscoft . NET Framework 3.5 Lab Manual', '', 'NULL')
INSERT INTO books(title, author, isbn) VALUES('FACSys Fax Messaging Gateway for Microsoft Windows NT', '', 'NULL')
INSERT INTO books(title, author, isbn) VALUES('Microsoft Exchange Server 2000', 'Andy Koopmans, et.al', 'NULL')
INSERT INTO books(title, author, isbn) VALUES('Microsoft SQL Server 2005: T-SQL Query Tuning and Optimization', 'Kalen Delaney', 'NULL')
INSERT INTO books(title, author, isbn) VALUES('SQL Server 2000 Database Design', 'Richard McMahon, Sean Chase', 'NULL')
INSERT INTO books(title, author, isbn) VALUES('Understanding & Programming COM+', 'Robert Oberg', 'NULL')
INSERT INTO books(title, author, isbn) VALUES('Windows 7 Professional & Enterprise - Quick Reference Guide', '', 'NULL')
INSERT INTO books(title, author, isbn) VALUES('Inside Microsoft SQL Server 2.5 2005 T-SQL Querying', 'Itzik Ben-Gan, Lubor Kollar, Dejan Sarka', 'NULL')
INSERT INTO books(title, author, isbn) VALUES('Teach yourself Microsoft Small Business Server 4.5 in 21 days', 'Harry Brelsford', 'NULL')
INSERT INTO books(title, author, isbn) VALUES('No-Limit Texas Hold''Em', 'Andrea Shavick, Dan Shavick', 'NULL')
INSERT INTO books(title, author, isbn) VALUES('SharePoint 2010 as a Development Platform', 'Krause, Langhirt, Sterff, Pehile, Doring', 'NULL')
INSERT INTO books(title, author, isbn) VALUES('JavaScript: The Good Parts', 'Douglas Crockford', 'NULL')
INSERT INTO books(title, author, isbn) VALUES('The Pocket Guide to Good Push', 'Urban Airship', 'NULL')
INSERT INTO books(title, author, isbn) VALUES('Flourish - A New Understanding of Happines and Well-Being', 'Martin Seligman', 'NULL')
INSERT INTO books(title, author, isbn) VALUES('DOM scripting', ' Jeremy Keith', '1430233893')
INSERT INTO books(title, author, isbn) VALUES('HTML5: Up and Running', 'Mark Pilgrim', '596806027')
INSERT INTO books(title, author, isbn) VALUES('Web style guide', 'Patrick J. Lynch', '300137370')
INSERT INTO books(title, author, isbn) VALUES('Oracle PL/SQL programming', ' Steven Feuerstein', '596514468')
INSERT INTO books(title, author, isbn) VALUES('Microsoft SQL server 2008 adminstrator''s pocket consultant', ' William R. Stanek', '735625891')
INSERT INTO books(title, author, isbn) VALUES('Securing SQL servers', ' Denny Cherry', '1597499471')
INSERT INTO books(title, author, isbn) VALUES('Spring Persistance with Hibernate', 'Paul Tepper Fisher, Brian D. Murphy', '978-1430226321')
INSERT INTO books(title, author, isbn) VALUES('T-SQL Fundamentals (Microsoft SQL Server 2008)', 'Itzik Ben-Gan', '978-8178531045')
INSERT INTO books(title, author, isbn) VALUES('Beginning Hibernate', ' Jeff Linwood', '1430228504')
INSERT INTO books(title, author, isbn) VALUES('JBoss in action', ' Javid Jamae', '1933988029')
INSERT INTO books(title, author, isbn) VALUES('Pro Spring', 'Rob Harrop, Jan Machacek', '978-1430241072')
INSERT INTO books(title, author, isbn) VALUES('Spring Enterprise Recipes', 'Josh Long, Gary Mak', '1430224975')
INSERT INTO books(title, author, isbn) VALUES('Next generation Java testing', ' Cédric Beust', '321503104')
INSERT INTO books(title, author, isbn) VALUES('SCJP Sun Certified Programmer for Java 6 Study Guide', 'Kathy Sierra, Bert Bates', '70264988')
INSERT INTO books(title, author, isbn) VALUES('Liferay in action', ' Rich Sezov', '193518282X')
INSERT INTO books(title, author, isbn) VALUES('Portlets in action', ' Ashish Sarin', '1935182544')
INSERT INTO books(title, author, isbn) VALUES('JBoss AS 5 Development', 'Francessco Marchioni', '1847196829')
INSERT INTO books(title, author, isbn) VALUES('Closing techniques (that really work!)', ' Stephan Schiffman', '1598698206')
INSERT INTO books(title, author, isbn) VALUES('Forming a Limited Company', 'Patricia clayton', '749453044')
INSERT INTO books(title, author, isbn) VALUES('Good to Great', 'Jim Collins', '66621003')
INSERT INTO books(title, author, isbn) VALUES('Managing Transitions', 'William Bridges ', '1857885414')
INSERT INTO books(title, author, isbn) VALUES('Mindset - The New Psychology Of Success', 'Carol . Dweck', '1780332009')
INSERT INTO books(title, author, isbn) VALUES('Presentation zen', ' Garr Reynolds', '321811984')
INSERT INTO books(title, author, isbn) VALUES('Running a limited company', ' David Impey', '1846612616')
INSERT INTO books(title, author, isbn) VALUES('Slack', ' Tom Demarco', '932633617')
INSERT INTO books(title, author, isbn) VALUES('Version Control with Git', 'Jon Loeliger', '978-1449316389')
INSERT INTO books(title, author, isbn) VALUES('50 Management Ideas You Really Need to Know', 'Edward Russell-Walling', '1847240097')
INSERT INTO books(title, author, isbn) VALUES('Brilliant Project Management', 'Stephen Barker, Rob Cole', '027377509X')
INSERT INTO books(title, author, isbn) VALUES('How to lead', ' Jo Owen', '273759612')
INSERT INTO books(title, author, isbn) VALUES('The 5 Essential People Skills', 'Dale Carnegie', '1847377645')
INSERT INTO books(title, author, isbn) VALUES('The project manager', 'Richard Newton', '273723421')
INSERT INTO books(title, author, isbn) VALUES('Execution:  The Discipline of Getting Things Done', 'Larry Bossidy, Ram Charan', '1847940684')
INSERT INTO books(title, author, isbn) VALUES('Computer Science - An Overview', 'J. Glenn Brookshear', '273751395')
INSERT INTO books(title, author, isbn) VALUES('Autotools', ' John Calcote', '1593272065')
INSERT INTO books(title, author, isbn) VALUES('Languages and Compilers for Parallel Computing', 'Utpal Banerjee, et.al', '3642360351')
INSERT INTO books(title, author, isbn) VALUES('Service-Oriented Architechure', 'Thomas Erl', '470376848')
INSERT INTO books(title, author, isbn) VALUES('Software Engineering, A Practitioner''s Approach', 'Roger Pressman', '71267824')
INSERT INTO books(title, author, isbn) VALUES('The Art of Computer Programming, volume 1, 2 and 3', 'Donald Knuth', '321751043')
INSERT INTO books(title, author, isbn) VALUES('The art of multiprocessor programming', ' Maurice Herlihy', '123973376')
INSERT INTO books(title, author, isbn) VALUES('Writing Secure Code', 'Michael Howard, David LeBlanc', '735617228')
INSERT INTO books(title, author, isbn) VALUES('Growing Object-Orientated Software, Guided by Tests', 'Steve Freeman, Nat Pryce', '321503627')
INSERT INTO books(title, author, isbn) VALUES('Introduction to Algorithms', 'T Cormen, C Leiserson, R Rivest, C Stein', '262533057')
INSERT INTO books(title, author, isbn) VALUES('Making Software, What Really Works and Why We Believe It', 'Andy Oram, Greg Wilson', '978-0596808327')
INSERT INTO books(title, author, isbn) VALUES('Mercurial', ' Bryan O''Sullivan', '596800673')
INSERT INTO books(title, author, isbn) VALUES('The clean coder', 'Robert C. Martin', '137081073')
INSERT INTO books(title, author, isbn) VALUES('The passionate programmer', ' Chad Fowler', '1934356344')
INSERT INTO books(title, author, isbn) VALUES('A first course in the numerical analysis of differential equations', ' A. Iserles', '521734908')
INSERT INTO books(title, author, isbn) VALUES('An Introduction to the Theory of Numbers', 'G. Hardy, E. Wright', '199219869')
INSERT INTO books(title, author, isbn) VALUES('Frank Wood''s business accounting 1', ' Frank Wood', '273759280')
INSERT INTO books(title, author, isbn) VALUES('Dubrovnik', 'Bradt', '1841621919')
INSERT INTO books(title, author, isbn) VALUES('English Vocabulary in Use', 'Stuart Redman', '521149886')
INSERT INTO books(title, author, isbn) VALUES('Tales of the DeCongested', 'Rebekah Lattin-Rawstrone, Paul Blaney', '955253802')
INSERT INTO books(title, author, isbn) VALUES('Why I Write', 'George Orwell', '014101900X')
INSERT INTO books(title, author, isbn) VALUES('Software Testing:  An ISEB Intermediate Certificate', 'Brian Hambling, Angelina Samaroo', '1906124132')
INSERT INTO books(title, author, isbn) VALUES('Hello Android - Introducing Google''s Mobile Development Platform', 'Ed Burnette', '9781930000000')
INSERT INTO books(title, author, isbn) VALUES('Unlocking Android', ' W. Frank Ableson', '1933988673')
INSERT INTO books(title, author, isbn) VALUES('iPhone SDK development', ' Bill Dudney', '1934356255')
INSERT INTO books(title, author, isbn) VALUES('Pro Android 2', ' Sayed Y. Hashimi', '1430226595')
INSERT INTO books(title, author, isbn) VALUES('Sams teach yourself C in 21 days', ' Bradley L. Jones', '672324482')
INSERT INTO books(title, author, isbn) VALUES('Sams teach yourself C++ in one hour a day', ' Siddhartha Rao', '672335670')
INSERT INTO books(title, author, isbn) VALUES('The C++ Programming Language', 'Bjarne Stroustrup', '321563840')
INSERT INTO books(title, author, isbn) VALUES('UNIX Network Programming, volume 2', 'W. Richard Stevens', '812032062X')
INSERT INTO books(title, author, isbn) VALUES('Actionscript developer''s guide to Robotlegs', ' Joel Hooks', '1449308902')
INSERT INTO books(title, author, isbn) VALUES('Adobe Flex Training from the Source vol 1.', 'Michael Labriola, Jeff Tapper, Matthew Boles', '321660501')
INSERT INTO books(title, author, isbn) VALUES('Eloquent Ruby', 'Russ Olsen', '321584104')
INSERT INTO books(title, author, isbn) VALUES('Grails in action', ' Glen Smith', '1933988932')
INSERT INTO books(title, author, isbn) VALUES('Professional Xcode 3', ' James Bucanek', '470525223')
INSERT INTO books(title, author, isbn) VALUES('Programming in Objective-C 2.0', 'Stephen G. Kochan', '032188728X')
INSERT INTO books(title, author, isbn) VALUES('Programming Perl', ' Tom Christiansen', '596004923')
INSERT INTO books(title, author, isbn) VALUES('Programming Ruby', 'Dave Thomas', '1937785491')
INSERT INTO books(title, author, isbn) VALUES('Programming Amazon Web Services', ' James Murty', '596515812')
INSERT INTO books(title, author, isbn) VALUES('The Rails 3 way', ' Obie Fernandez', '321601661')
INSERT INTO books(title, author, isbn) VALUES('Zend Framework 1.8 Web Application Development', 'Keith Pope', '1847194222')
INSERT INTO books(title, author, isbn) VALUES('Beginning Ruby', ' Peter Cooper', '1430223634')
INSERT INTO books(title, author, isbn) VALUES('Programming in Scala', ' Martin Odersky', '981531644')
INSERT INTO books(title, author, isbn) VALUES('MCTS self-paced training kit (Exam 70-502)', ' Matthew A. Stoecker', '735625662')
INSERT INTO books(title, author, isbn) VALUES('MCTS self-paced training kit (exam 70-562)', ' Mike Snell', '073562562X')
INSERT INTO books(title, author, isbn) VALUES('MCTS self-paced training kit (exam 70-680)', 'Ian McLean', '735627088')
INSERT INTO books(title, author, isbn) VALUES('Designing and developing ASP.NET applications using the Microsoft .NET Framework 3.5, exam 70-564', 'Microsoft Official Academic Course', '470551402')
INSERT INTO books(title, author, isbn) VALUES('Effective C♯', ' Bill Wagner', '321658701')
INSERT INTO books(title, author, isbn) VALUES('Architecting Microsoft  .NET solutions for the enterprise', ' Dino Esposito', '073562609X')
INSERT INTO books(title, author, isbn) VALUES('.NET application architecture guide', 'Microsoft', '073562710X')
INSERT INTO books(title, author, isbn) VALUES('Microsoft SQL Server 2008 step by step', ' Mike Hotek', '735626049')
INSERT INTO books(title, author, isbn) VALUES('Microsoft. NET Framework 3.5 - ASP.NET Application Development', 'Mike Snell, Glenn Johnson, Tony Northrup, and GrandMasters', '470551399')
INSERT INTO books(title, author, isbn) VALUES('More effective C♯', ' Bill Wagner', '321485890')
INSERT INTO books(title, author, isbn) VALUES('Pro WF', 'Bruce Bukovics', '1430227214')
INSERT INTO books(title, author, isbn) VALUES('Professional C# 4 and .Net 4', ' Christian Nagel', '470502258')
INSERT INTO books(title, author, isbn) VALUES('Microsoft SQL server 2008 reporting services step by step', ' Stacia Misner', '735626472')
INSERT INTO books(title, author, isbn) VALUES('Professional WCF 4 Windows Communication Foundation with  .NET 4', 'Pablo Cibraro, Kurt Claeys, Fabio Cozzolino, Johann Grabner', '470563141')
INSERT INTO books(title, author, isbn) VALUES('Programming C#', 'Jesse Liberty', '1449320414')
INSERT INTO books(title, author, isbn) VALUES('Programming Entity Framework', 'Julia Lerman', '596807260')
INSERT INTO books(title, author, isbn) VALUES('Programming Microsoft SQL Server 2008', ' Leonard Lobel', '735625999')
INSERT INTO books(title, author, isbn) VALUES('Sharepoint 2007 development recipes', ' Mark E. Gerow', '1430209615')
INSERT INTO books(title, author, isbn) VALUES('Silverlight 1.0 unleashed', ' Adam Nathan', '672330075')
INSERT INTO books(title, author, isbn) VALUES('SQL Server 2005', 'William R. Stanek', '8120329201')
INSERT INTO books(title, author, isbn) VALUES('Programming Microsoft SQL Server 2008', ' Leonard Lobel', '735625999')
INSERT INTO books(title, author, isbn) VALUES('SQL Server 2008 - Implementation and Maintenance - Training Kit', 'Mike Hotek', '9780740000000')
INSERT INTO books(title, author, isbn) VALUES('SQL Server 2008 Internals', 'Kalen Delaney', '735626243')
INSERT INTO books(title, author, isbn) VALUES('SQL Server 2008: T-SQL Querying', 'Itzik Ben-Gan', '735626030')
INSERT INTO books(title, author, isbn) VALUES('Mastering System center configuration manager 2007', ' Chris Mosby', '047017367X')
INSERT INTO books(title, author, isbn) VALUES('Sams teach yourself ASP.NET 4 in 24 hours complete starter kit', ' Scott Mitchell', '672333058')
INSERT INTO books(title, author, isbn) VALUES('Thinking of - Delivering Solutions on the Windows Azure Platform - Ask the Smart Questions', 'Dan Scarfe, Marcus Tillett, Stephen Parker', '956155634')
INSERT INTO books(title, author, isbn) VALUES('Thinking of - Maximising your Investment as a Microsoft Partner - Ask the Smart Questions', 'Julie Simpson, Andy Trish', '956155669')
INSERT INTO books(title, author, isbn) VALUES('Visual Basic 2008', ' Rod Stephens', '470182628')
INSERT INTO books(title, author, isbn) VALUES('MCTS self-paced training kit (exam 70-515)', ' Anthony Northrup', '735627401')
INSERT INTO books(title, author, isbn) VALUES('C# in Depth', 'Jon Skeet', '161729134X')
INSERT INTO books(title, author, isbn) VALUES('Accessing Data with Microsoft .NET framework 4', 'Glenn Johnson', '735627398')
INSERT INTO books(title, author, isbn) VALUES('Applied WPF 4 in context', ' Raffaele Garofalo', '1430234709')
INSERT INTO books(title, author, isbn) VALUES('ASP.NET 3.5 Unleashed', 'Stephen Walther', '672335646')
INSERT INTO books(title, author, isbn) VALUES('C# 4.0 in a Nutshell', 'Joseph Albahari, Ben Albahari', '596800959')
INSERT INTO books(title, author, isbn) VALUES('C# 4.0 Pocket Reference', 'Joseph Albahari, Ben Albahari', '1449394019')
INSERT INTO books(title, author, isbn) VALUES('CLR via C#', 'Jeffrey Richter', '735667454')
INSERT INTO books(title, author, isbn) VALUES('Functional programming in C#', ' Oliver Sturm', '470744588')
INSERT INTO books(title, author, isbn) VALUES('How we test software at Microsoft', ' Alan Page', '735624259')
INSERT INTO books(title, author, isbn) VALUES('Learning C#', 'Jesse/ MacDonald Liberty', '596521065')
INSERT INTO books(title, author, isbn) VALUES('Microsoft SharePoint 2010 unleashed', ' Michael Noel', '672333252')
INSERT INTO books(title, author, isbn) VALUES('Nhibernate 3 Beginners Guide', 'Dr. Gabriel Nicolas Schenker, Aaron Cure', '1849516022')
INSERT INTO books(title, author, isbn) VALUES('NHibernate in action', 'Pierre Kuate, Christian Bauer', '1932394923')
INSERT INTO books(title, author, isbn) VALUES('Pro ASP.NET MVC 3 Framework', 'Adam Freeman, Steven Sanderson', '1430234040')
INSERT INTO books(title, author, isbn) VALUES('Pro C# 2010 and the .NET 4 platform', ' Andrew W. Troelsen', '1430225491')
INSERT INTO books(title, author, isbn) VALUES('Pro WF Windows Workflow in .NET 4', 'Bruce Bukovics', '1430227214')
INSERT INTO books(title, author, isbn) VALUES('Pro WPF in C# 2010', 'Matthew MacDonald', '1430272058')
INSERT INTO books(title, author, isbn) VALUES('SharePoint Server 2010 Enterprise Content Management', 'Todd Kitta, Brett Grego, Chris Caplinger, Russ Houberg', '470584653')
INSERT INTO books(title, author, isbn) VALUES('Silverlight 3 Programmer''s Reference', ' J. Ambrose Little,  Jason Beres,  Grant Hinkson,  Devin Rader,  Joe Croney', '470385405')
INSERT INTO books(title, author, isbn) VALUES('WPF4 Unleashed', ' Adam Nathan', '978-0672331190')
INSERT INTO books(title, author, isbn) VALUES('Sun Certified Programmer for Java 6 Study Guide', 'Kathy Sierra, Bert Bates', '70264988')
INSERT INTO books(title, author, isbn) VALUES('Scala for the impatient', ' Cay S. Horstmann', '321774094')
INSERT INTO books(title, author, isbn) VALUES('The LEGO Mindstorms NXT 2.0 discovery book', ' Laurens Valk', '1593272111')
INSERT INTO books(title, author, isbn) VALUES('Professional WCF 4 Windows Communication Foundation with .NET 4', 'Pablo Cibraro, Kurt Claeys, Fabio Cozzolino, Johann Grabner', '978-0470563144')
INSERT INTO books(title, author, isbn) VALUES('MCTS self-paced training kit (exam 70-503)', ' Bruce Johnson', '735625654')
INSERT INTO books(title, author, isbn) VALUES('Coders at work', ' Peter Seibel', '1430219483')
INSERT INTO books(title, author, isbn) VALUES('Getting to Yes - Negotiating an Agreement Without Giving in', 'Roger Fisher, William Ury', '1847940935')
INSERT INTO books(title, author, isbn) VALUES('Programming Entity Framework: Code First', 'Julia Lerman, Rowan Miller', '1449312942')
INSERT INTO books(title, author, isbn) VALUES('Programming Entity Framework: DbContext', 'Julia Lerman, Rowan Miller', '1449312969')
INSERT INTO books(title, author, isbn) VALUES('The definitive guide to Pylons', ' James Gardner', '1590599349')
INSERT INTO books(title, author, isbn) VALUES('Test-driven iOS development', ' Graham Lee', '321774183')
INSERT INTO books(title, author, isbn) VALUES('Beginning Rails 3', 'Cloves Carneiro Jr., Rida Al Barazi', '1430224339')
INSERT INTO books(title, author, isbn) VALUES('Professional Android 4 application development', ' Reto Meier', '1118102274')
INSERT INTO books(title, author, isbn) VALUES('SharePoint 2010 DEvelopment with Visual Studio 2010', 'Carter, Scholl, & Jausovec', '321718313')
INSERT INTO books(title, author, isbn) VALUES('The Developer''s Code - What Real Programmers Do', 'Ka Wai Cheung', '1934356794')
INSERT INTO books(title, author, isbn) VALUES('Codermetrics', 'Jonathan Alexander', '978-1449305154')
INSERT INTO books(title, author, isbn) VALUES('JavaScript Patterns', 'Stoyan Stefanov', '596806752')
INSERT INTO books(title, author, isbn) VALUES('Learning ActionScript 3.0', 'Rich Shupe, Zevan Rosser', '144939017X')
INSERT INTO books(title, author, isbn) VALUES('The Social Executive', 'Sharif Khalladi', '1482361205')
INSERT INTO books(title, author, isbn) VALUES('Leading lean software development', ' Mary Poppendieck', '321620704')
INSERT INTO books(title, author, isbn) VALUES('Business analysis techniques', ' James Cadle', '190612423X')
INSERT INTO books(title, author, isbn) VALUES('Professional Sitecore Development', 'John West', '047093901X')
INSERT INTO books(title, author, isbn) VALUES('Effective C♯', ' Bill Wagner', '321658701')
INSERT INTO books(title, author, isbn) VALUES('Designing and Developing Web Applications Using Microsoft .NET Framework 4', 'Tony Northrup', '735657262')
INSERT INTO books(title, author, isbn) VALUES('Advanced Google AdWords', ' Brad Geddes', '1118194500')
INSERT INTO books(title, author, isbn) VALUES('Google AdWords', ' Anastasia Holdren', '1449308384')
INSERT INTO books(title, author, isbn) VALUES('The Ultimate Small Business Marketing Book', 'Dee Blick', '1905493770')
INSERT INTO books(title, author, isbn) VALUES('Switch ', 'Chip and Dan Heath', '1847940323')
INSERT INTO books(title, author, isbn) VALUES('Selling to Win', 'Richard Denny', '749466316')
INSERT INTO books(title, author, isbn) VALUES('Brilliant presentation', 'Richard Hall', '027376246X')
INSERT INTO books(title, author, isbn) VALUES('Bounce ', 'Matthew Syed', '7350546')
INSERT INTO books(title, author, isbn) VALUES('Exploratory software testing', ' James A. Whittaker', '321636414')
INSERT INTO books(title, author, isbn) VALUES('Refactoring', 'Martin Fowler', '')
INSERT INTO books(title, author, isbn) VALUES('Sams Teach Yourself Windows Server 2008', 'Joe Habraken', '')
INSERT INTO books(title, author, isbn) VALUES('test', 'test', '')
INSERT INTO books(title, author, isbn) VALUES('Service Design Patterns', 'Robert Daigneau', '')
INSERT INTO books(title, author, isbn) VALUES('Enterprise SOA', 'Dirk Krafzig, Karl Banke, Dirk Slama', '')
INSERT INTO books(title, author, isbn) VALUES('SOA Patterns', 'Arnon Rotem-Gal-Oz', '')
INSERT INTO books(title, author, isbn) VALUES('Perfect Software', 'Gerald M. Weinberg', '')
INSERT INTO books(title, author, isbn) VALUES('It''s Not Carpal Tunnel Syndrome', 'Suparna Damany, MSPT & Jack Bellis', '')
INSERT INTO books(title, author, isbn) VALUES('Play for Scala', 'Peter Hilton, Erik Bakker, Francisco Canedo', '')
INSERT INTO books(title, author, isbn) VALUES('Making It All Work', 'David Allen', '')
INSERT INTO books(title, author, isbn) VALUES('Ready For Anything', 'David Allen', '')
INSERT INTO books(title, author, isbn) VALUES('Vagrant: Up and Running', 'Mitchell Hashimoto', '')
INSERT INTO books(title, author, isbn) VALUES('Puppet 3 Cookbook, 2nd Edition', 'John Arundel', '')
INSERT INTO books(title, author, isbn) VALUES('Spring Web Services 2 Cookbook', 'Hamidreza Sattari, Shameer Kunjumohamed', '')
INSERT INTO books(title, author, isbn) VALUES('Actors in Scala', 'Philipp Haller, Frank Sommers', '')
INSERT INTO books(title, author, isbn) VALUES('Testing in Scala', 'O''Reilly', '')
INSERT INTO books(title, author, isbn) VALUES('Effective JAVA Script ', 'David Herman ', '')
INSERT INTO books(title, author, isbn) VALUES('Read This Before Our Next Meeting ', 'Al Pittampalli', '')
INSERT INTO books(title, author, isbn) VALUES('Software Estimation ', 'Steve McConnell ', '')
INSERT INTO books(title, author, isbn) VALUES('PHP and MySql Everyday Apps for Dummies ', 'Janet Valade', '')
INSERT INTO books(title, author, isbn) VALUES('F# for C# Developers ', 'Tao Liu', '')
INSERT INTO books(title, author, isbn) VALUES('Facts and Fallacies of Software Engineering', 'Robert L Glass', '')
INSERT INTO books(title, author, isbn) VALUES('Db Context', 'Julia Lerman and Rowan Miller', '')
INSERT INTO books(title, author, isbn) VALUES('Configuring Advanced Windows Server 2012 R2 Services', 'J.C Mackin / Orin Thomas', '')
INSERT INTO books(title, author, isbn) VALUES('The Solutions Focus', 'Paul Z Jackson / Mark McKergow', '')
INSERT INTO books(title, author, isbn) VALUES('Being Geek', 'Michael Lopp', '')
INSERT INTO books(title, author, isbn) VALUES('Managing Humans', 'Michael Lopp ', '')
INSERT INTO books(title, author, isbn) VALUES('Clojure Programming ', 'Chas Emerick, Brian Carper, Christophe Grand', '')
INSERT INTO books(title, author, isbn) VALUES('FISH!', 'Stephen C Lundin Ph.D', '')
INSERT INTO books(title, author, isbn) VALUES('Seven Languages in Seven Weeks', 'Bruce A. Tate', '')
INSERT INTO books(title, author, isbn) VALUES('Java Concurrency in Practice', 'Brian Goetz', '')
INSERT INTO books(title, author, isbn) VALUES('The Magic Book of Thinking', 'David J. Schwartz', '')
INSERT INTO books(title, author, isbn) VALUES('To Sell Is Human', 'Daniel H. Pink', '')
INSERT INTO books(title, author, isbn) VALUES('Business Model Generation', 'Alexander Osterwalder & Yves Pigneur', '')
INSERT INTO books(title, author, isbn) VALUES('Learning Perl', 'Randal L Schwartz/Tom Phoenix', '')
INSERT INTO books(title, author, isbn) VALUES('Intermediate Perl', 'Randal L Schwartz/Tom Phoenix', '')
INSERT INTO books(title, author, isbn) VALUES('Galvanizing the Geeks', 'Zoe Cunningham', '')
INSERT INTO books(title, author, isbn) VALUES('Developing ASP.NET MVC4 Web Applications (Exam Ref 70-486)', 'William Penberthy', '')
INSERT INTO books(title, author, isbn) VALUES('Programming in HTML5 with JavaScript and CSS3', 'Rick Delorme', '')
INSERT INTO books(title, author, isbn) VALUES('Little Miss Geek', 'Belinda Parmar', '')
INSERT INTO books(title, author, isbn) VALUES('Java Performance', 'Charlie Hunt and Binu John', '')
INSERT INTO books(title, author, isbn) VALUES('Spring in Practice', 'Willie Wheeler with Joshua White', '')
INSERT INTO books(title, author, isbn) VALUES('Pro Angular JS', 'Adam Freeman ', '')
INSERT INTO books(title, author, isbn) VALUES('The Joy of Clojure ', 'Michael Fogus/Chris Houser', '')
INSERT INTO books(title, author, isbn) VALUES('High Performance Websites', 'Steve Souders', '')
INSERT INTO books(title, author, isbn) VALUES('The Art of Capacity Planning', 'John Allspaw', '')
INSERT INTO books(title, author, isbn) VALUES('Building Scalable Web Sites', 'Cal Henderson', '')
INSERT INTO books(title, author, isbn) VALUES('Scalable Internet Architectures', 'Theo Schlossnagle', '')
INSERT INTO books(title, author, isbn) VALUES('Becoming a Technical Leader', 'Gerald M Weinberg', '')
INSERT INTO books(title, author, isbn) VALUES('Computer Networking', 'James F. Kurose, Keith W. Ross', '')
INSERT INTO books(title, author, isbn) VALUES('xUnit Test Patterns', 'Gerard Meszaros', '')
INSERT INTO books(title, author, isbn) VALUES('Apprenticeship Patterns', 'David H.Hoover & Adeale Oshineye', '')
INSERT INTO books(title, author, isbn) VALUES('Understanding Crytography', 'Christof Paar/Jan Pelzl', '')
INSERT INTO books(title, author, isbn) VALUES('The Signal and the Noise', 'Nate Silver', '')
INSERT INTO books(title, author, isbn) VALUES('Thinking, Fast and Slow', 'Daniel Kahneman', '')
INSERT INTO books(title, author, isbn) VALUES('Lean Analytics', 'Eric Ries', '')
INSERT INTO books(title, author, isbn) VALUES('SSH Mastery ', 'Michael W. Lucas', '')
INSERT INTO books(title, author, isbn) VALUES('Bulletproof SSL and TLS', 'Ivan Ristic', '')
INSERT INTO books(title, author, isbn) VALUES('Configuring Windows Server Virtualization', 'Nelson Ruest, Danielle Ruest and Grandmasters', '')
INSERT INTO books(title, author, isbn) VALUES('Networking and Network Access Protection (NAP)', 'Joseph Davies and Tony Northrup with the Microsoft Networking Team', '')
INSERT INTO books(title, author, isbn) VALUES('Building Microservices', 'Sam Newman', '')
INSERT INTO books(title, author, isbn) VALUES('Getting Started with OAuth 2.0', 'Ryan Boyd', '')
INSERT INTO books(title, author, isbn) VALUES('Programming in C#, exam ref 70-483', 'Wouter de Kort', '')
INSERT INTO books(title, author, isbn) VALUES('Pro C# 5.0 and the .NET 4.5 Framework', 'Andrew Troelsen', '')
INSERT INTO books(title, author, isbn) VALUES('The art of looking sideways.', 'Alan Fletcher', '')
INSERT INTO books(title, author, isbn) VALUES('Wireshark 101', 'Laura Chappell', '')
INSERT INTO books(title, author, isbn) VALUES('Brilliant Communication Skills', 'Gill Hasson', '')
INSERT INTO books(title, author, isbn) VALUES('Business Writing', 'Ian Atkinson', '')
INSERT INTO books(title, author, isbn) VALUES('Professional ASP.NET MVC 5', 'Jon Galloway, Brad Wilson, K. Scott Allen & David Matson', '')
INSERT INTO books(title, author, isbn) VALUES('Essentials of Developing Windows Store App Using C#', 'Indrajit Chakrabarty', '')
INSERT INTO books(title, author, isbn) VALUES('Programming in C#', 'Wouter de Kort', '')
INSERT INTO books(title, author, isbn) VALUES('Debugging', 'David J. Agans', '')
INSERT INTO books(title, author, isbn) VALUES('Developing Windows Azure and Web Services (Exam Ref 70-487)', 'William Ryan, Wouter de Kort & Shane Milton', '')
INSERT INTO books(title, author, isbn) VALUES('Notes to a Software Team Leader', 'Roy Osherove', '')
INSERT INTO books(title, author, isbn) VALUES('Talking with Tech Leads', 'Patrick Kua', '')
INSERT INTO books(title, author, isbn) VALUES('Managing Successful Projects with PRINCE2', 'TSO', '')
INSERT INTO books(title, author, isbn) VALUES('Smart Investing', 'Tim Hale', '')
INSERT INTO books(title, author, isbn) VALUES('Playing Poker to Win', 'Andrea Shavick & Dan Shavick', '')
INSERT INTO books(title, author, isbn) VALUES('Somebody Should Have Told Us!', 'Jack Pransky', '')
INSERT INTO books(title, author, isbn) VALUES('Practical Vim', 'Drew Neil', '')


